default: &default
  :url: "http://elasticsearch:9200"
  :transport_options:
    :request:
      :timeout: 5

development:
  <<: *default

test:
  <<: *default
  :transport_options:
    :request:
      :timeout: 3000

production:
  :url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("cosmetics-elasticsearch")["uri"] %>
