version: '3'

services:
  db:
    image: beisopss/db:${TRAVIS_BUILD_NUMBER}

  keycloak:
    environment:
      - NOTIFY_API_KEY
    image: beisopss/keycloak:${TRAVIS_BUILD_NUMBER}

  maintenance:
    image: beisopss/maintenance:${TRAVIS_BUILD_NUMBER}

  cosmetics-web:
    command: tail -f /dev/null
    image: beisopss/cosmetics-web:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
      - ~/coverage-cache/cosmetics:/cosmetics-web/coverage
    environment:
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - SEARCH_HOST=localhost
      - SUBMIT_HOST=localhost
  cosmetics-worker:
    command: tail -f /dev/null
    image: beisopss/cosmetics-worker:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - elasticsearch
      - keycloak
      - redis
    command: elasticsearch:9200 keycloak:8080
