version: '3'

services:
  db:
    image: ${DOCKER_USERNAME}/db:${TRAVIS_BUILD_NUMBER}
  
  keycloak:
    environment:
      - NOTIFY_API_KEY='fake-key'
    image: ${DOCKER_USERNAME}/keycloak:${TRAVIS_BUILD_NUMBER}
  
  antivirus:
    image: ${DOCKER_USERNAME}/antivirus:${TRAVIS_BUILD_NUMBER}

  cosmetics-web:
    command: tail -f /dev/null
    image: ${DOCKER_USERNAME}/cosmetics-web:${TRAVIS_BUILD_NUMBER}
    volumes:
    - ~/bundle-cache:/usr/local/bundle
    environment:
    - CI
    - TRAVIS
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - COVERALLS_PARALLEL
  cosmetics-worker:
    command: tail -f /dev/null
    image: ${DOCKER_USERNAME}/cosmetics-worker:${TRAVIS_BUILD_NUMBER}
    volumes:
    - ~/bundle-cache:/usr/local/bundle
  
  mspsds-web:
    command: tail -f /dev/null
    image: ${DOCKER_USERNAME}/mspsds-web:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
    environment:
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - COVERALLS_PARALLEL
      - NOTIFY_API_KEY='fake-key'
  mspsds-worker:
    command: tail -f /dev/null
    image: ${DOCKER_USERNAME}/mspsds-worker:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
  
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - elasticsearch
      - keycloak
      - redis
    command: elasticsearch:9200 keycloak:8080
