version: 1

update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"

  # - package_manager: "java:maven"
  #   directory: "/keycloak/providers/email"
  #   update_schedule: "daily"

  # - package_manager: "java:maven"
  #   directory: "/keycloak/providers/registration-form"
  #   update_schedule: "daily"

  # - package_manager: "java:maven"
  #   directory: "/keycloak/providers/rest-api"
  #   update_schedule: "daily"

  # - package_manager: "java:maven"
  #   directory: "/keycloak/providers/system-out-event-listener"
  #   update_schedule: "daily"

  - package_manager: "javascript"
    directory: "/cosmetics-web"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/maintenance"
    update_schedule: "live"

  - package_manager: "ruby:bundler"
    directory: "/antivirus"
    update_schedule: "live"

  - package_manager: "ruby:bundler"
    directory: "/cosmetics-web"
    update_schedule: "live"
    version_requirement_updates: off

  - package_manager: "ruby:bundler"
    directory: "/infrastructure/fluentd"
    update_schedule: "live"
